### ISSUE TITLE
Some questions about this project！

### ISSUE THREAD

**Issue by bingpo** [ARPSyndicate/kenzer#10]
Can this project be scanned offline? How do I install and run it? Just like nuclei, can I install it to Kali Linux? In many cases, my computer is offline, but I want to scan my internal server and application website. Another thing, can kenzer's vulnerability template also be added to nuclei I for vulnerability scanning

**Comment by g147** [comment]
hey! no kenzer is not a vulnerability scanner. its just an automation engine for enumeration & scanning of externally facing assets. for scanning vulnerabilities, it utilizes nuclei & jaeles & yeah the templates can be used & have been categorized accordingly. if you are looking for application testing then you should tryout utilities like wapiti, owasp zap, vega, burpsuite, etc.

**Comment by bingpo** [comment]
> hey! no kenzer is not a vulnerability scanner. its just an automation engine for enumeration & scanning of externally facing assets. for scanning vulnerabilities, it utilizes nuclei & jaeles & yeah the templates can be used & have been categorized accordingly. if you are looking for application testing then you should tryout utilities like wapiti, owasp zap, vega, burpsuite, etc.

Thank you for your reply！have a nice day！
