### ISSUE TITLE
install.sh checks for system binaries rather than potentially duplicating with kenzer-bin

### ISSUE THREAD

**Issue by daehee** [ARPSyndicate/kenzer#2]
Rather than clone `kenzer-db` with pre-existing binaries, it would be ideal if `install.sh` downloads specified kenzer-compatible executable for each tool from their official repos.

**Comment by g147** [comment]
some of the third party tools i have been using have been modified by us to fit our needs. the best we can do is ask user if they want to install binaries from `kenzer-bin` or not.

**Comment by g147** [comment]
fixed in 758e7931c9e0202120de3ee9b7e4d98e911c64a1
