### ISSUE TITLE
bug: after first run of install.sh, only outputs up to "training chatterbot"

### ISSUE THREAD

**Issue by daehee** [ARPSyndicate/kenzer#3]
Expected: `[*] KENZER is online` info to stdout

Got:
<img width="460" alt="CleanShot 2020-10-20 at 12 19 47@2x" src="https://user-images.githubusercontent.com/81271/96633981-b68a1e00-12ce-11eb-8fed-08340022ebe0.png">

**Comment by g147** [comment]
fixed in 0fcbe4bab7a269113291fa3eddf9b05edc07d248
