### ISSUE TITLE
OSError: [E941] Can't find model 'en'.

### ISSUE THREAD

**Issue by osama-set** [ARPSyndicate/kenzer#4]
Getting this error when i am running kenzer.
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/74716056/107619376-e5a90e80-6c74-11eb-83bb-83eecc59bdc5.png">

**Comment by g147** [comment]
python3 -m spacy download en_core_web_sm

**Comment by osama-set** [comment]
I am still getting the same error:

<img width="1661" alt="image" src="https://user-images.githubusercontent.com/74716056/107734585-94098e00-6d1f-11eb-9360-80629cdcb72c.png">

**Comment by g147** [comment]
pip3 install -U spacy==1.9.0

**Comment by osama-set** [comment]
Thanks @g147 the fixed my issue but now when i send command to kenzer server i am not getting any response.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/74716056/107795730-dc09ce80-6d7a-11eb-9fe6-d7e646778e73.png">
<img width="871" alt="image" src="https://user-images.githubusercontent.com/74716056/107795696-d1e7d000-6d7a-11eb-9857-02e40a541faa.png">

**Comment by g147** [comment]
Make sure the bot name is correct & is subscribed to the channel. If the email is kenzer-bot@xyz.com then bot's name is kenzer.

**Comment by osama-set** [comment]
Still not getting the response from the kenzer server here is my kenzer.conf:

```
[env]
home=/root/

[kenzerdb]
path=/root/kenzer/kenzerdb/directory/
token=tokenvalue
user=osama-set
repo=https://github.com/osama-set/kenzerdb.git

[kenzer]
email=kenzer-bot@xyz.zulipchat.com
path=/root/kenzer/
key=keyvalue
site=https://xyz.zulipchat.com
uploads=False
subscribe=True
```


<img width="953" alt="image" src="https://user-images.githubusercontent.com/74716056/107844120-a274aa00-6df2-11eb-9f6b-580dce4ae0ee.png">

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/74716056/107844125-adc7d580-6df2-11eb-8d1e-5239ac40b093.png">

**Comment by g147** [comment]
what is the |389365 ? Is it getting logged everytime you send that command?

**Comment by osama-set** [comment]
the key is valid this number is send from zulip its self.

**Comment by g147** [comment]
try copy pasting  - @\*\*kenzer\*\* man
