### ISSUE TITLE
Bot doesn`t reply 

### ISSUE THREAD

**Issue by m19o** [ARPSyndicate/kenzer#6]
I did the configuration and configured the bot and nothing happen when i type a command

**Comment by M19O** [comment]
<img src="https://i.ibb.co/WDcLKMG/kenzer.png" alt="kenzer" border="0">
<img src="https://i.ibb.co/87kQcpf/kenzer2.png" alt="kenzer2" border="0">

**Comment by m19o** [comment]
@g147  ?

**Comment by g147** [comment]
oh hey! apologies for the late reply. i was on a break from all this stuff. so here it looks like the name of your chatbot isn't right and you haven't subscribed it to stream and communicating through private message instead. the part before -bot in the bot's email is its name and you gotta add it to a stream first then communicate through it. writing just @ in stream's conversation will bring up list of participants and your bot will be able to talk back and forth just like discord or any other chat platform.

**Comment by M19O** [comment]
check this : 

<img src="https://i.ibb.co/Kbw2r0H/2021-09-25-12-50-10.png" alt="2021-09-25-12-50-10" border="0">
<img src="https://i.ibb.co/QPbqRBJ/2021-09-25-12-50-33.png" alt="2021-09-25-12-50-33" border="0">

**Comment by g147** [comment]
the spelling of False is not right for splitting and that may or may not result into invalid configuration error but rest seems great and ` @**kenzer** man ` should show manual.

**Comment by m19o** [comment]
It worked
